In [58]:
import pandas as pd
df = pd.read_csv('/content/data_sw.csv')

In [59]:
# List the first 5 characters from the DataFrame.

df.head(5)

,Personagem,Espécie,Planeta,Poder_Forca,Habilidade_Combate,Ano_Nascimento
0,Luke Skywalker,Humano,Tatooine,51,52,-32
1,Darth Vader,Sith,Tatooine,92,1,-76
2,Leia Organa,Humano,Alderaan,14,87,-40
3,Han Solo,Humano,Corellia,71,29,17
4,Obi-Wan Kenobi,Humano,Stewjon,60,37,-36

In [60]:
# What are the unique species in the dataset?

df['Espécie'].value_counts()

Espécie
Humano          9
Sith            2
Droid           2
Yoda Species    1
Wookiee         1
Name: count, dtype: int64

In [61]:
# What is the average Force Power by Species?

df.groupby('Espécie')['Poder_Forca'].mean().sort_values(ascending=False)

Espécie
Sith            89.500000
Wookiee         82.000000
Droid           80.000000
Humano          46.111111
Yoda Species    20.000000
Name: Poder_Forca, dtype: float64

In [62]:
# Use groupby() to calculate the average Force Power by Planet and determine where the most powerful characters come from.

df.groupby('Planeta')['Poder_Forca'].mean().sort_values(ascending=False)

Planeta
Socorro         99.000000
Kashyyyk        82.000000
Kamino          74.000000
Tatooine        72.333333
Corellia        71.000000
Naboo           64.666667
Stewjon         60.000000
Haruun Kal      23.000000
Desconhecido    20.000000
Alderaan        14.000000
Coruscant        2.000000
Name: Poder_Forca, dtype: float64

In [63]:
# Filter the characters who have a Force Power greater than 50.

df[df['Poder_Forca'] > 50]

,Personagem,Espécie,Planeta,Poder_Forca,Habilidade_Combate,Ano_Nascimento
0,Luke Skywalker,Humano,Tatooine,51,52,-32
1,Darth Vader,Sith,Tatooine,92,1,-76
3,Han Solo,Humano,Corellia,71,29,17
4,Obi-Wan Kenobi,Humano,Stewjon,60,37,-36
6,Chewbacca,Wookiee,Kashyyyk,82,63,40
7,R2-D2,Droid,Naboo,86,59,-40
8,C-3PO,Droid,Tatooine,74,20,44
9,Boba Fett,Humano,Kamino,74,32,-70
10,Emperor Palpatine,Sith,Naboo,87,75,-18
11,Lando Calrissian,Humano,Socorro,99,57,-73

In [64]:
# Create a new column called "Power Category" based on the Force Power level.

df['Categoria_De_Poder'] = df['Poder_Forca'].apply(lambda x: 'Jedi Master' if x > 80 else 'Sem Sensibilidade' if x < 30 else 'Padawan')
df.head()

,Personagem,Espécie,Planeta,Poder_Forca,Habilidade_Combate,Ano_Nascimento,Categoria_De_Poder
0,Luke Skywalker,Humano,Tatooine,51,52,-32,Padawan
1,Darth Vader,Sith,Tatooine,92,1,-76,Jedi Master
2,Leia Organa,Humano,Alderaan,14,87,-40,Sem Sensibilidade
3,Han Solo,Humano,Corellia,71,29,17,Padawan
4,Obi-Wan Kenobi,Humano,Stewjon,60,37,-36,Padawan

In [65]:
# Sort the DataFrame by Combat Skill level in descending order.

df.sort_values('Habilidade_Combate', ascending=False)

,Personagem,Espécie,Planeta,Poder_Forca,Habilidade_Combate,Ano_Nascimento,Categoria_De_Poder
13,Qui-Gon Jinn,Humano,Coruscant,2,88,-2,Sem Sensibilidade
2,Leia Organa,Humano,Alderaan,14,87,-40,Sem Sensibilidade
10,Emperor Palpatine,Sith,Naboo,87,75,-18,Jedi Master
6,Chewbacca,Wookiee,Kashyyyk,82,63,40,Jedi Master
7,R2-D2,Droid,Naboo,86,59,-40,Jedi Master
11,Lando Calrissian,Humano,Socorro,99,57,-73,Jedi Master
0,Luke Skywalker,Humano,Tatooine,51,52,-32,Padawan
14,Padmé Amidala,Humano,Naboo,21,48,-31,Sem Sensibilidade
4,Obi-Wan Kenobi,Humano,Stewjon,60,37,-36,Padawan
9,Boba Fett,Humano,Kamino,74,32,-70,Padawan
3,Han Solo,Humano,Corellia,71,29,17,Padawan
12,Mace Windu,Humano,Haruun Kal,23,21,41,Sem Sensibilidade
8,C-3PO,Droid,Tatooine,74,20,44,Padawan
1,Darth Vader,Sith,Tatooine,92,1,-76,Jedi Master
5,Yoda,Yoda Species,Desconhecido,20,1,-27,Sem Sensibilidade

In [66]:
# Find the character with the highest Combat Skill.

df[df['Habilidade_Combate'] == df['Habilidade_Combate'].max()]

,Personagem,Espécie,Planeta,Poder_Forca,Habilidade_Combate,Ano_Nascimento,Categoria_De_Poder
13,Qui-Gon Jinn,Humano,Coruscant,2,88,-2,Sem Sensibilidade

In [67]:
# Apply a style to the DataFrame to highlight in red the characters with Force Power greater than 80.

def highlight_name(value):
    return 'font-weight: bold; color: red' if (df[df['Personagem'] == value]['Poder_Forca'] > 80).any() else ''

df.style.map(highlight_name, subset=['Personagem'])

In [68]:
# What is the average age of characters at the time of the Battle of Yavin (Year 0)?

df_filtered_2 = df[df['Ano_Nascimento'] <= 0]
idade = -(df_filtered_2['Ano_Nascimento'].mean())
print(f"{idade:.2f}")

40.45